# Generated by Django 2.2.3 on 2022-05-26 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('last_execution', models.CharField(max_length=50, null=True)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComputingInfrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('about_url', models.CharField(max_length=250)),
                ('infra_type', models.CharField(choices=[('HPC', 'HPC'), ('OPENSTACK', 'OpenStack'), ('EOSC', 'EOSC-Hub')], max_length=10)),
                ('interface', models.CharField(choices=[('SLURM', 'Slurm'), ('TORQUE', 'Torque'), ('BASH', 'Bash')], max_length=6)),
                ('definition', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceExecution',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField(null=True)),
                ('execution_time', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('CANCELLING', 'Cancelling'), ('FORCE_CANCELLING', 'Force Cancelling'), ('CANCELLED', 'Cancelled'), ('TERMINATED', 'Terminated'), ('FAILED', 'Failed'), ('QUEUED', 'Queued'), ('SCHEDULED', 'Scheduled')], default='PENDING', max_length=17)),
                ('has_errors', models.BooleanField(default=False)),
                ('num_errors', models.IntegerField(default=0)),
                ('current_task', models.CharField(max_length=50, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croupier.AppInstance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='DataCatalogueKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComputingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croupier.ComputingInfrastructure')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('main_blueprint_file', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('included', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('is_new', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_advertised', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='appinstance',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croupier.Application'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
