# Generated by Django 2.2.3 on 2019-09-12 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croupier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputingInfrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('about_url', models.CharField(max_length=250)),
                ('infra_type', models.CharField(choices=[('HPC', 'HPC'), ('OPENSTACK', 'OpenStack'), ('EOSC', 'EOSC-Hub')], max_length=10)),
                ('interface', models.CharField(choices=[('SLURM', 'Slurm'), ('TORQUE', 'Torque'), ('BASH', 'Bash')], max_length=5)),
                ('definition', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataCatalogueKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComputingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croupier.ComputingInfrastructure')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
